### ISSUE TITLE
Maintain Bank setting becomes enabled before clicking Save

### ISSUE THREAD

**Issue by paulellery** [greenc/CookieMaster#64] opened 2014-03-07 16:17 UTC
In the Settings > Experimental page, checking or unchecking the "Maintain Bank" option makes the feature immediately active - without having to click Save.

(Unless this is deliberate), the setting should only be applied once a user clicks Save

**Comment by greenc** [comment] 2014-03-07 17:19
This is not exactly intentional, however some settings that don't require runtime changes will take effect when toggled, without the user needing to explicitly click the save button.

I may look into changing it so that settings only update on save, which will provide a more uniform experience.

I'm closing this issue as it's not a bug, and not a high priority feature.

**Closed as completed by greenc** 2014-03-07 17:19 UTC
